#!/usr/bin/env python

from chdrft.waf.opa import WafBuilder

x = WafBuilder(globals())

x.register_libs(x.packages.Glm, x.libs.Common_N, x.libs.MathCommon_N, x.libs.OR_N,
                x.packages.OpenCV, x.libs.Algo_N, x.packages.CGAL, x.packages.FPLLL,
                x.libs.MathGameProto_N, x.libs.Algo_N)
x.auto()
x.get(x.typ.LIB).update(register_name=x.libs.MathCO_N, features='cxxshlib')
x.setup()
