#!/usr/bin/env python

from chdrft.waf.opa import WafBuilder

x = WafBuilder(globals())

x.register_libs([x.packages.GMP, x.packages.MPFR, x.libs.Common_N, x.libs.MathCommon_N])
x.auto()
x.get(x.typ.LIB).update(register_name=x.libs.MathAdv_N,
                        includes='./inc/opa/math/adv',
                        features='cxxshlib',
                        basename='mathadv')

x.setup()
