#!/usr/bin/env python

from chdrft.waf.opa import WafBuilder


x = WafBuilder(globals())
x.register_libs(x.libs.Common_N)
x.auto()

x.get(x.typ.LIB).update(register_name=x.libs.OR_N)
x.get(x.typ.SWIG_H).update(register_name=x.libs.ORSwig_N)
x.get(x.typ.SWIG).update(install=True)
x.setup()
