#!/usr/bin/env python

from chdrft.waf.opa import WafBuilder

x = WafBuilder(globals())

x.register_libs(x.packages.ZeroMQ, x.packages.Protoc, x.packages.Protobuf,
                x.libs.Common_N, x.libs.MathCommon_N)
x.auto()
x.get(x.typ.LIB).update(register_name=x.libs.Threading_N,
                        includes='./inc/opa/threading',
                        features='cxxshlib')
x.get(x.typ.SWIG).update(install=True)
x.setup()

#ctx.install_files(ctx.env.PYTHON_INSTALL_DIR, './runner/run.py')
#ctx(features='python rpc',
#    source=['./proto/server.proto'],
#    target='thread_master',)
