#!/usr/bin/env python

from chdrft.waf.opa import WafBuilder, ExtraConf

x = WafBuilder(globals())

x.register_libs(x.libs.Engine_N)

x.create_conf(x.typ.SAMPLE, 'mipmap_gen').update(
    features='cxx',
    sources='./mipmap_gen.cpp')
x.create_conf(x.typ.SAMPLE, 'missing_tiles').update(
    features='cxx',
    sources='./create_missing_tiles.cpp')
x.auto()

x.setup()
