#!/usr/bin/env python

from chdrft.waf.opa import WafBuilder

x = WafBuilder(globals())

x.auto()
x.get(x.typ.LIB).update(register_name=x.libs.Crypto_N,
                        includes='./inc/opa/crypto',
                        features='cxxshlib',
                        libs=[x.packages.OpenSSL, x.libs.Common_N,
                              x.libs.MathCommon_N, x.libs.Threading_N],
                        install=True)
x.get(x.typ.SWIG).update(install=True, libs=x.libs.SwigMathCommon_N)
x.setup()
